### ISSUE TITLE
Make code PEP8 compliant using yapf

### ISSUE THREAD

**Issue by doaa-altarawy** [SrinivasMushnoori/RepEx_3.0#14]
Use yapf to style your code to be PEP8 compliant. It will fix extra lines, some missing spaces, long lines. It will NOT fix variable names.

In terminal:
`pip install yapf`

Then modify files in place:
```
yapf -i filename
yapf -i -r directory_name
```

**Comment by SrinivasMushnoori** [comment]
Addressed and pushed to devel.

**Comment by SrinivasMushnoori** [comment]
Capitalizations and naming conventions will be handled as per #15
