### ISSUE TITLE
Python naming convensions

### ISSUE THREAD

**Issue by doaa-altarawy** [SrinivasMushnoori/RepEx_3.0#15]
More changes are needed for the code to follow python naming conventions. PEP8 describes Python best practices for naming conventions [here](https://www.python.org/dev/peps/pep-0008/#naming-conventions).

1. Packages and modules (filenames and folder names) are all lowercase, use underscore if really needed
1. Classes and types are CamelCase, they are the only thing that's camelCase.
1. functions and variables (including function arguments) are snake case; lowercase separated by underscore when needed.
1. Constant are all capital letters separated with underscores.

**Comment by SrinivasMushnoori** [comment]
Fixed in https://github.com/SrinivasMushnoori/repex/commit/3a1d3ae3e98e8f6e0b8a772891b690e89630c11a (mostly, hopefully I haven't missed anything)
