### ISSUE TITLE
gromacs executable

### ISSUE THREAD

**Issue by s10021205** [SrinivasMushnoori/RepEx_3.0#30]
Hi there, I have recently downloaded the Repex which is successfully downloaded. Although the installation works well, the problem comes from user guide. 
Where I try to run: repex simconfig.json resconfig.json
The error message shows: md_executable.
I sent the email to my colleague, Srinivas, for help. He suggested me to change the path to the gromacs executable folder.
I have tried that but the same error message shows. 
(p.s. the imagines show how I changed the path.)
![2019-02-28 08-54-57](https://user-images.githubusercontent.com/43686023/53575171-071f9700-3b3f-11e9-837d-8381da10fc6f.jpg)
![2019-02-28 09-56-21](https://user-images.githubusercontent.com/43686023/53575336-5cf43f00-3b3f-11e9-9dcd-bed8b0216b7f.jpg)

**Comment by SrinivasMushnoori** [comment]
1) What _exactly_ is the error? Is it a key error? Value error? Can you post the error traceback?
2) `home/Jerry/.../gromacs/build/bin` is the directory. You want to add to that a 'gmx' at the end, like `......build/bin/gmx`

**Comment by s10021205** [comment]
raceback (most recent call last):
  File "/usr/local/bin/repex", line 4, in <module>
    __import__('pkg_resources').run_script('repex==3.0.2', 'repex')
  File "/home/jerry/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jerry/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/repex-3.0.2-py2.7.egg/EGG-INFO/scripts/repex", line 41, in <module>
    
KeyError: 'md_executable'

I have added gmx at the end.

**Comment by SrinivasMushnoori** [comment]
Try this:

`cd` into your repex folder.
```
git checkout devel
pip install . --upgrade
```

Then try running the example.

**Comment by SrinivasMushnoori** [comment]
Actually ignore the above. 
Try this
`repex simconfig.json resconfig_local.json`

**Comment by SrinivasMushnoori** [comment]
Jerry, I've pushed a patch to devel. It should work now. 
```
git checkout devel
pip install . --upgrade
```
And then try.

**Comment by s10021205** [comment]
I have tried the two commands you posted git checkout and pip install in repex folder.
Then I go to experiemtns folder where the two files inside which are simconfig_local.json resconfig_local.json
Quick question, in reconfig_local.json, I need to change the md_executable path? Or don't need to change anything?

**Comment by s10021205** [comment]
![2019-02-28 11-50-00](https://user-images.githubusercontent.com/43686023/53583272-3dfda900-3b4f-11e9-808e-8a5c82311a30.jpg)

**Comment by SrinivasMushnoori** [comment]
Yes, you should change it to
```
home/Jerry/.../gromacs/build/bin/gmx
```

**Comment by s10021205** [comment]
what about py_executable?

**Comment by SrinivasMushnoori** [comment]
That should be your python executable 
Do the following:

```
which python
```

that will return the location of your python executable. Copy/paste that into the python executable field.

**Comment by s10021205** [comment]
Ok, anything I need to change before I execute the code?

![2019-02-28 12-02-15](https://user-images.githubusercontent.com/43686023/53584111-eb24f100-3b50-11e9-868e-115d4ec17bce.jpg)

**Comment by SrinivasMushnoori** [comment]
Wait, why is it `usr/bin/python` ?
Are you not using a virtual environment? 

If not, you should be. Do the following:

```
cd
mkdir VirtualEnvs
cd VirtualEnvs
virtualenv repex
source repex/bin/activate
```
cd to your repex folder

```
git checkout devel
pip install . --upgrade
```

Then do a `which python` and paste THAT python executable in your `resconfig_local.json`

**Comment by SrinivasMushnoori** [comment]
Thanks for bringing this up: I should make it more explicitly clear in my user guide that the user is expected to always start from a virtual environment.

**Comment by s10021205** [comment]
![2019-02-28 12-20-49](https://user-images.githubusercontent.com/43686023/53585259-7901db80-3b53-11e9-8c31-68da0d0d84c0.jpg)

**Comment by SrinivasMushnoori** [comment]
Please see previous comment.

**Comment by s10021205** [comment]
Hi Srinivas!
This is what I have in resconfig_local.json, please have a look.
Any comment?
"resource"      : "local.localhost",
        "md_executable" : "/home/jerry/下載/gromoacs-2018.4/build/bin/gmx",
        "py_executable" : "/home/jerry/VirtualEnvs/repex/bin/python",
        "pre_exec"      : "export amber_md=amber_14", 
	"walltime"      : 60,
	"cpus"          : 4

**Comment by SrinivasMushnoori** [comment]
Should be fine.

**Comment by s10021205** [comment]
Hi Srinivas!
I believe I am in the Virtual Environment 
I tried 
 repex simconfig.json resconfig_local.json 
And it shows the following error in the picture. (Sorry for the late update.)
![2019-03-04 19-49-31](https://user-images.githubusercontent.com/43686023/53773064-d9c44780-3eb6-11e9-8144-15f4c2c2ee0e.png)

**Comment by SrinivasMushnoori** [comment]
What branch are you on? Please do `git branch` and tell me the output.

**Comment by s10021205** [comment]
(repex) jerry@jerry-VirtualBox:~/repex/experiments$ git branch
* devel
  master

**Comment by SrinivasMushnoori** [comment]
What are the contents of `simconfig.json` ?

**Comment by s10021205** [comment]
"replicas"       : 24,
	"replica_cores"  : 1,
	"cycles"         : 1,
        "exchange_method" : "exchangeMethods/TempEx.py", 
	"md_executable"  : "/home/jerry/下載/gromoacs-2018.4/build/bin/gmx", 
	"timesteps"      : 100,
	"basename"       : "ace-ala"

**Comment by SrinivasMushnoori** [comment]
You're using the incorrect simconfig file. You are using the one from the `master` branch, but you are on `devel`. 

```
{
	"replicas"       : 32,
	"replica_cores"  : 1,
	"cycles"         : 0,
        "exchange_method" : "exchangeMethods/TempEx.py", 
	"md_executable"  : "/home/jerry/下載/gromoacs-2018.4/build/bin/gmx",
	"timesteps"      : 100,
	"basename"       : "basename",
        "min_temp"       : 300,
        "max_temp"       : 550
        
    
}

```

https://github.com/SrinivasMushnoori/repex/blob/devel/examples/simconfig.json

Change your "basename" to the basename of your system.

**Comment by s10021205** [comment]
Based on the website.
2.1.2 Basename

RepEx needs a basename to locate the files which will be used as input parameters for the MD component. These may include (depending on the MD engine) a coordinate file, a topology file, and a run-input file.
That means I need to copy and paste the path where the topology file is?
For example:  /home/jerry/下載/v6k2_coil

**Comment by SrinivasMushnoori** [comment]
Please study this example: https://github.com/SrinivasMushnoori/repex/tree/usecase/peptide_gromacs/examples/gromacs_example

You MIGHT need to do the following:
```
git checkout usecase/gromacs
pip install . --upgrade
```

**Comment by s10021205** [comment]
(repex) jerry@jerry-VirtualBox:~/repex$ git checkout usecase/gromacs
error: pathspec 'usecase/gromacs' did not match any file(s) known to git.

**Comment by SrinivasMushnoori** [comment]
Apologies, it's `usecase/peptide_gromacs`

**Comment by s10021205** [comment]
(repex) jerry@jerry-VirtualBox:~/repex$ usecase/peptide_gromacs
bash: usecase/peptide_gromacs: no such file or directory

**Comment by s10021205** [comment]
git checkout usecase/peptide_gromacs
M	examples/simconfig.json
M	experiments/resconfig_local.json
M	experiments/simconfig.json
M	tests/simconfig.json
Branch 'usecase/peptide_gromacs' set up to track remote branch 'usecase/peptide_gromacs' from 'origin'.
Switched to a new branch 'usecase/peptide_gromacs'

**Comment by s10021205** [comment]
There is one more thing I want to add. 
On the user guide section of the website, it shows  
repex simconfig.json resconfig.json 
Which is perfect but can you let the user know which is the specific folder (tests, experiments, examples) that to execute the code. 
In my case, in the examples folder, there is no reconfig.json
                 in the tests folder, I get both
                 in the experiments folder, there is no reconfig.json.
Also, the same thing for the examples section. For me, I need to go to the tests folder instead of examples one.  thanks!

**Comment by SrinivasMushnoori** [comment]
Thanks, Jerry.
Yes there are multiple changes I need to make in the documentation and sync a few branches. 

Did it work?

**Comment by s10021205** [comment]
Morning! Yes it works and what's next?
git checkout usecase/peptide_gromacs
M	examples/simconfig.json
M	experiments/resconfig_local.json
M	experiments/simconfig.json
M	tests/simconfig.json
Branch 'usecase/peptide_gromacs' set up to track remote branch 'usecase/peptide_gromacs' from 'origin'.
Switched to a new branch 'usecase/peptide_gromacs'

**Comment by SrinivasMushnoori** [comment]
Okay good. I'm going to close this ticket now, since this is resolved. Please study the peptide gromacs example and set up your own system in a similar manner.
