### ISSUE TITLE
Exchange Task is not getting triggered, possibly an overload

### ISSUE THREAD

**Issue by SrinivasMushnoori** [SrinivasMushnoori/RepEx_3.0#33]
https://github.com/SrinivasMushnoori/repex/commit/9071a0742f89501255f2cd9ec680a06118ed92b7

The above commit results in the `check_exchange` method not pushing the exchange list to the exchange task. Possibly because the `exchange_list` name is being overloaded. Investigating.

**Comment by andre-merzky** [comment]
You may want to begin using `pylint` - it will flag warnings if a local variable overloads a parameters, etc.  It cannot find all errors of that type (as Python leaves you a lot of freedom here), but some, and also checks for other common error types.

```
pip install pylint
pylint file.py
```

You will initially see *many* warnings, mostly about coding style and conventions.  Let us know if you need a pylint config file to silence some of those.

**Comment by SrinivasMushnoori** [comment]
This does not look like an overload. Very strange. The `exchange_list`is actually being returned _late,_ somehow. Looking into it.

**Comment by andre-merzky** [comment]
Let me know if you want me to look into this.  How do you run the code?

**Comment by SrinivasMushnoori** [comment]
Will do, thanks. Running short diagnostics, which are returning some conflicting information. 
Now I'm beginning to think we are indeed looking at the correct replica's local list, but something is going wrong in `_check_resume`. Will continue to look into it.

**Comment by SrinivasMushnoori** [comment]
As far as I am able to tell, we are triggering the exchange task now. Closing, will reopen if needed.
