### ISSUE TITLE
New MD stage not triggering after EX

### ISSUE THREAD

**Issue by SrinivasMushnoori** [SrinivasMushnoori/RepEx_3.0#34]
Lin 475 in [sliding window](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py) is as follows:

```
    def _after_ex(self):
        '''
        after an ex cycle, trigger replica resumption
        '''
        self._check_res(self)
```

`self._check_res(self)` is basically [_check_resume](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L308). In line 319, i.e.:

`for _r in replica.exchange_list`

`_check_resume` requires a `replica.exchange_list`. However, this is a `NoneType` object that causes the new MD stage trigger to fail. [Line 362](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L362) in the `Replica` class initializes the `exchange_list` as `self._ex_list=None` which is then reassigned as `self._ex_list=exchange_list` in [Line 442](https://github.com/SrinivasMushnoori/repex/blob/am/restructure/examples/async_sliding_window.py#L442)

However this assignment is not communicated to the Exchange object that tries to trigger the resume method. Unsure how to set up the MD trigger to pull the list from the replica itself. 

Investigating.

**Comment by SrinivasMushnoori** [comment]
This has been resolved and can be closed.

**Comment by andre-merzky** [comment]
What was it?

**Comment by SrinivasMushnoori** [comment]
This was because of incorrect indentation. This, however, is a _separate_ issue from [this EnTK issue](https://github.com/radical-cybertools/radical.entk/issues/353) where `pipeline.resume()` appears to fail. That has the same _symptom_ of a certain subset of MD tasks to never spawn, but unrelated to this ticket.

**Comment by andre-merzky** [comment]
Ah, of course - I thought of radical-cybertools/radical.entk/issues/353 indeed...
